server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: service-consumer
        uri: lb://service-consumer
        predicates:
          - Path=/cc/**
        filters:
          - StripPrefix=1 #如果链接为http://localhost:8888/test/abc/test 将会转发到http://localhost:8081/abc/test，去掉URL路径中的1个前缀，没有配置只是把IP改改变了转发
      - id: taobao
        uri: https://www.taobao.com/
        predicates:
          - Path=/taobao/**
  consul:
    enabled: true
    host: 127.0.0.1
    port: 8500
    discovery:
      healthCheckPath: /actuator/health
      healthCheckInterval: 5s
      instanceId: gateway-service
      register: true
      enabled: true

#用了consul 这个就没有用了
#eureka:
 # instance:
  #  prefer-ip-address: true
  #client:
   # service-url:
    #  defaultZone: http://localhost:8761/eureka/