server:
  port: 8082
spring:
  application:
    name: service-provider

#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: 127.0.0.1
    port: 6379
    password: jawave
    timeout: 2000
    # 服务或应用名
    sysName: service-provider
    enable: true
    database: 0




